name: Build and Package
on:
  push:
    branches: [ main ]
jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_NAME: vlc
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up environment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential devscripts debhelper dh-make
        
    - name: Create packages directory
      run: |
        mkdir packages
        
    - name: Create debian/changelog file
      run: |
        mkdir -p ${{ env.PACKAGE_DIR }}/debian
        touch ${{ env.PACKAGE_DIR }}/debian/changelog
      env:
        PACKAGE_DIR: "packages"
    
    - name: Build package
      run: |
        cd ${{ env.PACKAGE_DIR }}
        debuild -us -uc
      env:
        PACKAGE_DIR: "packages"
        
    - name: Save package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_DIR }}/*.deb
