name: Build and Publish Package
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      package:
        description: 'The name of the package to build and publish'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git
    - name: Configure package
      run: ./configure
    - name: Make package
      run: make package PACKAGE=${{ github.event.inputs.package }}
    - name: Publish package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.package }}-package
        path: ./${{ github.event.inputs.package }}-*.deb
  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.event.inputs.package }}-package
    - name: Publish to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ github.event.inputs.package }}:latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
