name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: vlc

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up apt dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential debhelper devscripts

      - name: Build package
        run: |
          cd ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
          debuild -uc -us

      - name: Save package to GitHub repository
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}.deb
