name: Build and publish package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: vlc
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential debhelper devscripts
    - name: Build package
      run: |
        cd debian
        debuild -us -uc
    - name: Publish package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ../${{ env.PACKAGE_NAME }}*.deb
