name: Build and Publish Apt Package

on:
  push:
    branches:
      - main

env:
  PACKAGE_NAME: ${{ github.event.inputs.package_name }}

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code and setup Node.js 16.x
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: 'recursive'
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential dh-make devscripts fakeroot
          mkdir -p ${PACKAGE_NAME}-1.0
          cd ${PACKAGE_NAME}-1.0 && DEBIAN_FRONTEND=noninteractive dh_make -p ${PACKAGE_NAME}_1.0 --createorig
          cd ..
          echo "${PACKAGE_NAME} (1.0) UNRELEASED; urgency=medium\n\n  * Initial release\n\n -- Your Name <yourname@yourdomain.com>  $(date -R)" > ${PACKAGE_NAME}-1.0/debian/changelog
      - name: Build package
        run: |
          cd ${PACKAGE_NAME}-1.0
          dpkg-buildpackage -uc -us
          cd ..
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}_${{ github.run_number }}
          path: '${PACKAGE_NAME}-1.0/*.deb'
      - name: Publish to Github Packages
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.packages.publishPackage({
              package_type: 'deb',
              name: process.env.PACKAGE_NAME,
              version: '${{ github.run_number }}',
              release_type: 'stable',
              package_file: `${{ github.event.repository.name }}_${{ github.run_number }}.deb`,
            })
            console.log(`Published package ${data.package.name} with version ${data.package.version}`)
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
